spring:
  batch:
    initialize-schema: always
    
app:
  datasource:
    wqp:
      url: NWIS_WS_STAR_URL
      username: NWIS_WS_STAR_USERNAME
      password: NWIS_WS_STAR_PASSWORD
      
    natdb:
      url: NATDB_URL
      username: NATDB_USERNAME
      password: NATDB_PASSWORD